version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webtorrent
  - dependency-name: got
  - dependency-name: del
  - dependency-name: nw-builder